name: ieqa
channels:
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38hca72f7f_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38hecd8cb5_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.4.26=hecd8cb5_0
  - certifi=2022.6.15=py38hecd8cb5_0
  - cffi=1.15.0=py38hc55c11b_1
  - dbus=1.13.18=h18a8e69_0
  - debugpy=1.5.1=py38he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=he9d5cce_0
  - gettext=0.21.0=h7535e17_0
  - glib=2.69.1=h8346a28_1
  - icu=58.2=h0a44026_3
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.9.1=py38hecd8cb5_0
  - ipython=8.4.0=py38hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38hecd8cb5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=hca72f7f_0
  - jsonschema=4.4.0=py38hecd8cb5_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38hecd8cb5_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libiconv=1.16=hca72f7f_2
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libxml2=2.9.14=hbf8cd5e_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - markupsafe=2.1.1=py38hca72f7f_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h1de35cc_1001
  - nbclient=0.5.13=py38hecd8cb5_0
  - nbconvert=6.4.4=py38hecd8cb5_0
  - nbformat=5.3.0=py38hecd8cb5_0
  - ncurses=6.3=hca72f7f_3
  - nest-asyncio=1.5.5=py38hecd8cb5_0
  - notebook=6.4.11=py38hecd8cb5_0
  - openssl=1.1.1q=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py38hecd8cb5_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.18.0=py38hca72f7f_0
  - python=3.8.13=hdfd78df_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pyzmq=23.2.0=py38he9d5cce_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.3.1=py38hecd8cb5_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=hca72f7f_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38hecd8cb5_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=h707629a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38hecd8cb5_0
  - testpath=0.6.0=py38hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.1=py38h9ed2024_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hecd8cb5_0
  - xz=5.2.5=hca72f7f_1
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.8.0=py38hecd8cb5_0
  - zlib=1.2.12=h4dc903c_2
  - pip:
    - autoflake==1.4
    - black==22.6.0
    - cfgv==3.3.1
    - click==8.1.3
    - distlib==0.3.5
    - filelock==3.7.1
    - identify==2.5.1
    - isort==5.10.1
    - mypy-extensions==0.4.3
    - nodeenv==1.7.0
    - pathspec==0.9.0
    - platformdirs==2.5.2
    - pre-commit==2.20.0
    - pyflakes==2.4.0
    - pyyaml==6.0
    - toml==0.10.2
    - tomli==2.0.1
    - virtualenv==20.15.1
prefix: /Users/ilyalasy/opt/anaconda3/envs/ieqa
